### ISSUE TITLE
Add some simple math operation to the code

### ISSUE THREAD

**Issue by nakul-py** [kinesis19/C_Programming_Applications#1]
### *add math operation in the practice file*

- ## *assign this to me*

**Comment by nakul-py** [comment]
\assign

**Comment by kinesis19** [comment]
Hi @nakul-py !
It's nice to meet u.

I appreciate your contribution to my repository, which is a personal repository that I'm studying and practicing on, so I can't merge it.

However, I'm happy to refer to your logic and study it further, so thank you for your contribution!
